#!/usr/bin/env bash
# Configure CellScope env vars inside WSL.
# Usage: source scripts/setup_wsl_envs.sh
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export CELLSCOPE_SPARQL_ENDPOINT="${CELLSCOPE_SPARQL_ENDPOINT:-http://localhost:3030/cellscope/update}"
export CELLSCOPE_SPARQL_TOKEN="${CELLSCOPE_SPARQL_TOKEN:-}"
export CELLSCOPE_SPARQL_USER="${CELLSCOPE_SPARQL_USER:-}"
export CELLSCOPE_SPARQL_PASSWORD="${CELLSCOPE_SPARQL_PASSWORD:-}"
export CELLSCOPE_SPARQL_OUTPUT="${CELLSCOPE_SPARQL_OUTPUT:-$ROOT_DIR/out-lab/index/last_update.sparql}"
export CELLSCOPE_SPARQL_RETRIES="${CELLSCOPE_SPARQL_RETRIES:-3}"
export CELLSCOPE_SPARQL_BACKOFF="${CELLSCOPE_SPARQL_BACKOFF:-1.5}"
export CELLSCOPE_SPARQL_TIMEOUT="${CELLSCOPE_SPARQL_TIMEOUT:-30}"
export JUPYTER_CONFIG_DIR="${JUPYTER_CONFIG_DIR:-$ROOT_DIR/.jupyter-config}"
mkdir -p "$JUPYTER_CONFIG_DIR"
cat <<'EOF'
CellScope WSL environment configured.
  CELLSCOPE_SPARQL_ENDPOINT=$CELLSCOPE_SPARQL_ENDPOINT
  CELLSCOPE_SPARQL_OUTPUT=$CELLSCOPE_SPARQL_OUTPUT
  CELLSCOPE_SPARQL_RETRIES=$CELLSCOPE_SPARQL_RETRIES
  CELLSCOPE_SPARQL_BACKOFF=$CELLSCOPE_SPARQL_BACKOFF
  CELLSCOPE_SPARQL_TIMEOUT=$CELLSCOPE_SPARQL_TIMEOUT
  JUPYTER_CONFIG_DIR=$JUPYTER_CONFIG_DIR
EOF
